package groundtruth

import (
	"fmt"
	"math"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// Verdict is the classification result for one detected claim.
// VerdictPass is the zero value so a Claim with no resolved verdict
// short-circuits cleanly through any "did we find a verdict?" check
// in caller code.
type Verdict int

const (
	// VerdictPass means the detector did not classify the span as a
	// claim. Callers typically drop these from output.
	VerdictPass Verdict = iota

	// VerdictVerified means the claim matched an entry in facts.yaml.
	// Claim.EvidencePath identifies the matching path.
	VerdictVerified

	// VerdictUnverified means the claim was detected by a pattern but
	// no facts.yaml entry matched. v0.7's pre-edit guard surfaces
	// these as warnings; v0.6 only logs them.
	VerdictUnverified

	// VerdictForbidden means the claim matches a do-not-claim.md rule.
	// Claim.RulePath / Claim.RuleText carry the citation.
	VerdictForbidden

	// VerdictOpinion means the span is a preference/value statement
	// ("I prefer", "I believe"). Not verifiable against facts; logged
	// for the audit trail and otherwise ignored.
	VerdictOpinion

	// VerdictContradiction means the span contains a number that is
	// within one order of magnitude of a numeric fact but does not
	// match exactly, AND a word near the number matches a segment of
	// the fact's path (e.g. "99 engineers" vs facts.team.engineers=12).
	// Treated as exit-1 (unverified tier) until precision is established.
	VerdictContradiction
)

// String returns the lowercase enum spelling for telemetry / log
// output / MCP wire format.
func (v Verdict) String() string {
	switch v {
	case VerdictPass:
		return "pass"
	case VerdictVerified:
		return "verified"
	case VerdictUnverified:
		return "unverified"
	case VerdictForbidden:
		return "forbidden"
	case VerdictOpinion:
		return "opinion"
	case VerdictContradiction:
		return "contradiction"
	default:
		return "unknown"
	}
}

// Claim is one detected span with its verdict and provenance. The
// shape mirrors the JSON schema that the verify_claim MCP tool (#10)
// will return — keeping them aligned now avoids a wire-format
// translation layer later.
type Claim struct {
	// Text is the substring of the input that matched a pattern.
	// Already trimmed of surrounding punctuation.
	Text string

	// Category is the pattern key that fired
	// ("personal_action", "quantitative", "tech_in_production",
	// "date", "opinion", "forbidden"). Useful for telemetry and
	// for letting Claude know which lane a claim was scored against.
	Category string

	// Verdict is the classification result.
	Verdict Verdict

	// EvidencePath identifies the facts.yaml node that satisfied a
	// VerdictVerified claim ("tech_stack.primary_language").
	// Empty for other verdicts.
	EvidencePath string

	// EvidenceValue is the raw value the facts walk returned for a
	// VerdictVerified claim. Carried for caller display.
	EvidenceValue any

	// RulePath identifies the do-not-claim.md rule that triggered a
	// VerdictForbidden ("Product capability gaps#3" — category +
	// 1-based rule-within-category index). Empty for other verdicts.
	RulePath string

	// RuleText is the verbatim forbidden text from do-not-claim.md.
	RuleText string

	// RuleReason is the operator-written explanation that follows
	// the forbidden text after the em-dash separator. Surfaced in
	// deny messages so the operator and the model see WHY the
	// claim is forbidden, not just THAT it is (#88).
	RuleReason string

	// Note carries free-text commentary used by VerdictOpinion to
	// explain why the span was treated as non-verifiable. Empty for
	// other verdicts.
	Note string

	// StartByte / EndByte are the input substring offsets where the
	// match was found. Callers (the post-edit hook in #18, the
	// pre-edit hard guard in #23) use these to highlight the
	// offending span back to Claude.
	StartByte int
	EndByte   int
}

// DetectionResult is what Detect returns. Claims is per-span; Summary
// is the rollup.
type DetectionResult struct {
	Claims  []Claim
	Summary Summary
}

// Summary holds per-verdict counts. Generated by Detect from the
// Claims slice so callers don't have to re-walk.
type Summary struct {
	Total          int
	Verified       int
	Unverified     int
	Forbidden      int
	Opinion        int
	Contradiction  int
}

// patternEntry pairs a compiled regex with the category and capture
// index that produces the "claim subject" — the substring used for
// the facts lookup. For most patterns the subject is the whole match;
// for personal-action it's the verb's object (capture 2).
type patternEntry struct {
	category string
	re       *regexp.Regexp
	// subjectGroup is the capture index whose text we look up against
	// facts.yaml. 0 = the whole match. -1 = no facts lookup; this
	// category is its own verdict (opinion).
	subjectGroup int
	// verdict overrides the lookup for opinion-like patterns. When
	// set to anything other than VerdictPass, the detector returns
	// that verdict directly without consulting facts.
	verdict Verdict
}

// patterns is the v0.6 seed set. Conservative: better to miss a claim
// than fabricate one. #13 (false-positive corpus) will tune these.
//
// The patterns are intentionally anchored on common high-signal
// constructions ("I shipped X", "production Go") so the false-positive
// rate stays low. Catching every claim in arbitrary prose is the v1.0
// hybrid (heuristic + LLM) target — see roadmap open question 5.
// Patterns run in priority order. More specific patterns come first so
// they consume overlapping spans before less specific ones get a
// chance. Span-overlap dedup is what enforces this — see the loop in
// Detect.
var patterns = []patternEntry{
	{
		category:     "opinion",
		re:           regexp.MustCompile(`(?i)\bI\s+(prefer|believe|think|feel|value)\b`),
		subjectGroup: 0,
		verdict:      VerdictOpinion,
	},
	{
		// More specific than personal_action: a known tech verb +
		// known language. Runs first so "I shipped Go" emits a
		// tech_in_production claim (the more meaningful category)
		// instead of personal_action.
		category:     "tech_in_production",
		re:           regexp.MustCompile(`(?i)\b(production|shipped|live)\s+(Go|Python|TypeScript|JavaScript|Java|Ruby|Rust|C\+\+|C#|PHP|Swift|Kotlin|Scala|Elixir|Haskell)\b`),
		subjectGroup: 2,
	},
	{
		category:     "personal_action",
		re:           regexp.MustCompile(`(?i)\bI\s+(built|shipped|created|launched|wrote|designed|architected)\s+([A-Za-z0-9_+#\.\-/]+)`),
		subjectGroup: 2,
	},
	{
		// "years", "months", "days" dropped from units: temporal
		// durations in prose ("13 years of experience", "took 6
		// months") almost never appear as scalar facts in
		// facts.yaml and produce a high unverified-claim noise rate.
		category:     "quantitative",
		re:           regexp.MustCompile(`(?i)\b(\d+(?:,\d{3})*(?:\.\d+)?)\s*(messages|users|customers|requests|MB|GB|TB|%)\b`),
		subjectGroup: 1,
	},
	{
		// Date pattern matches YYYY-MM-DD anywhere or a bare calendar
		// year (1900–2099). Bare-year is restricted to (?:19|20)\d{2}
		// so phone-number fragments like "1389" don't fire. The
		// YYYY-MM-DD form is listed first so the longer span wins via
		// overlap-dedup.
		category:     "date",
		re:           regexp.MustCompile(`\b(\d{4}-\d{2}-\d{2}|(?:19|20)\d{2})\b`),
		subjectGroup: 1,
	},
}

// broadNumberRe matches standalone numbers (comma-formatted or plain)
// at word boundaries. Used by the contradiction scan to find every
// numeric value in prose before comparing against facts.yaml leaves.
var broadNumberRe = regexp.MustCompile(`\b(\d+(?:,\d{3})*(?:\.\d+)?)\b`)

// numericLeafEntry is a numeric scalar from facts.yaml with its dotted path.
type numericLeafEntry struct {
	path  string
	value float64
}

// collectNumericLeaves walks the facts tree and returns every numeric
// scalar leaf (int, int64, float64) with its dotted path.
func collectNumericLeaves(facts *Facts) []numericLeafEntry {
	if facts.IsEmpty() {
		return nil
	}
	var out []numericLeafEntry
	walkNumericLeaves(facts.Root, "", &out)
	return out
}

func walkNumericLeaves(node any, path string, out *[]numericLeafEntry) {
	switch v := node.(type) {
	case map[string]any:
		for k, child := range v {
			childPath := k
			if path != "" {
				childPath = path + "." + k
			}
			walkNumericLeaves(child, childPath, out)
		}
	case []any:
		for i, child := range v {
			childPath := fmt.Sprintf("%s[%d]", path, i)
			walkNumericLeaves(child, childPath, out)
		}
	case int:
		*out = append(*out, numericLeafEntry{path: path, value: float64(v)})
	case int64:
		*out = append(*out, numericLeafEntry{path: path, value: float64(v)})
	case float64:
		*out = append(*out, numericLeafEntry{path: path, value: v})
	}
}

// numericOOM reports whether a and b are within one order of magnitude
// of each other (i.e. their floor(log10) values differ by at most 1).
func numericOOM(a, b float64) bool {
	if a <= 0 || b <= 0 {
		return false
	}
	oa := math.Floor(math.Log10(a))
	ob := math.Floor(math.Log10(b))
	return math.Abs(oa-ob) <= 1
}

// isYearRange reports whether v looks like a calendar year (1900–2100).
// Year-like integers are excluded from the contradiction scan to avoid
// false hits against year-valued facts and temporal prose.
func isYearRange(v float64) bool {
	return v >= 1900 && v <= 2100 && v == math.Trunc(v)
}

// numberContext returns up to 3 words before and 3 words after the
// byte span [start, end) in text. Used to determine whether a number's
// surrounding prose matches a fact's path segments.
func numberContext(text string, start, end int) string {
	prefixWords := strings.Fields(text[:start])
	if len(prefixWords) > 3 {
		prefixWords = prefixWords[len(prefixWords)-3:]
	}
	suffixWords := strings.Fields(text[end:])
	if len(suffixWords) > 3 {
		suffixWords = suffixWords[:3]
	}
	all := make([]string, 0, len(prefixWords)+len(suffixWords))
	all = append(all, prefixWords...)
	all = append(all, suffixWords...)
	return strings.Join(all, " ")
}

// contextMatchesFact reports whether any path segment from factPath
// (split on '.', '_', '[', ']') appears as a substring in ctx
// (case-insensitive). Segments shorter than 3 chars are skipped to
// avoid spurious matches on short words like "id" or "at".
func contextMatchesFact(ctx, factPath string) bool {
	segments := strings.FieldsFunc(factPath, func(r rune) bool {
		return r == '.' || r == '_' || r == '[' || r == ']'
	})
	lowerCtx := strings.ToLower(ctx)
	for _, seg := range segments {
		seg = strings.ToLower(seg)
		if len(seg) < 3 {
			continue
		}
		if strings.Contains(lowerCtx, seg) {
			return true
		}
	}
	return false
}

// Detect runs the heuristic detector against text using facts and
// rules from the loaded ground-truth tree. Returns one Claim per
// match. The returned slice is in source-order.
//
// Verdict priority per span (the FIRST winning rule decides):
//
//  1. Forbidden  — exact-string match against any rule.Text. (#13
//     adds fuzzy matching; v0.6 is strict so the false-positive
//     baseline is unambiguous.)
//  2. Opinion    — matches an opinion pattern. Skip facts lookup.
//  3. Pattern    — matches any other category pattern, then:
//     - VerdictVerified if the subject is found in facts.yaml
//     - VerdictUnverified otherwise
//
// Overlapping pattern matches are dropped: once a claim has been
// emitted at byte offset [start,end), any later pattern that overlaps
// that range is ignored. This keeps "I shipped Go in production"
// from emitting both a personal_action AND a tech_in_production
// claim for the same span.
func Detect(text string, facts *Facts, rules Rules) DetectionResult {
	var out []Claim

	// Forbidden hits come first because they should win regardless
	// of which detection pattern would also have fired. Uses fuzzy
	// matching when the rule's FuzzThreshold is positive; threshold
	// 0 falls through to the exact-string path.
	for i, rule := range rules {
		if rule.Text == "" {
			continue
		}
		matches := findFuzzyOccurrences(text, rule.Text, rule.FuzzThreshold)
		for _, m := range matches {
			out = append(out, Claim{
				Text:       text[m.start:m.end],
				Category:   "forbidden",
				Verdict:    VerdictForbidden,
				RulePath:   fmt.Sprintf("%s#%d", rule.Category, i+1),
				RuleText:   rule.Text,
				RuleReason: rule.Reason,
				StartByte:  m.start,
				EndByte:   m.end,
			})
		}
	}

	// Contradiction scan: find text numbers that differ from a numeric
	// fact within one order of magnitude, with a context word that
	// matches a segment of that fact's path. Runs after forbidden scan
	// (so forbidden beats contradiction) and before pattern scan (so
	// contradiction claims occupy their spans first).
	leaves := collectNumericLeaves(facts)
	if len(leaves) > 0 {
		for _, idx := range broadNumberRe.FindAllStringSubmatchIndex(text, -1) {
			start, end := idx[0], idx[1]
			if spanOverlapsAny(start, end, out) {
				continue
			}
			numStr := strings.ReplaceAll(text[idx[2]:idx[3]], ",", "")
			textVal, err := strconv.ParseFloat(numStr, 64)
			if err != nil || isYearRange(textVal) {
				continue
			}

			// Pass 1: if any leaf exactly matches the text number, skip —
			// let the pattern scan verify it normally.
			exactMatch := false
			for _, leaf := range leaves {
				if !isYearRange(leaf.value) && leaf.value == textVal {
					exactMatch = true
					break
				}
			}
			if exactMatch {
				continue
			}

			// Pass 2: emit a contradiction if any leaf is OOM-close AND
			// the surrounding context words match the leaf's path.
			ctx := numberContext(text, start, end)
			for _, leaf := range leaves {
				if isYearRange(leaf.value) {
					continue
				}
				if numericOOM(textVal, leaf.value) && contextMatchesFact(ctx, leaf.path) {
					out = append(out, Claim{
						Text:          strings.TrimRight(text[start:end], ".,;!?"),
						Category:      "contradiction",
						Verdict:       VerdictContradiction,
						EvidencePath:  leaf.path,
						EvidenceValue: leaf.value,
						StartByte:     start,
						EndByte:       end,
					})
					break
				}
			}
		}
	}

	// Walk the pattern set in priority order. Skip any match that
	// overlaps a span we've already emitted (forbidden hit OR a
	// higher-priority pattern that fired first).
	for _, p := range patterns {
		idxs := p.re.FindAllStringSubmatchIndex(text, -1)
		for _, idx := range idxs {
			start, end := idx[0], idx[1]
			if spanOverlapsAny(start, end, out) {
				continue
			}

			matchText := text[start:end]

			// F015: bare calendar years (no '-') in temporal
			// context are references, not factual claims. Skip
			// years preceded by temporal prepositions so "in
			// 2010", "since 2015", "until 2026" don't flood the
			// unverified-claims ledger. Full YYYY-MM-DD dates
			// aren't affected — they carry enough specificity to
			// be worth checking.
			if p.category == "date" && !strings.Contains(matchText, "-") {
				if isTemporalYearContext(text, start) {
					continue
				}
			}

			subject := matchText
			if p.subjectGroup > 0 && len(idx) >= 2*(p.subjectGroup+1) {
				ss, se := idx[2*p.subjectGroup], idx[2*p.subjectGroup+1]
				if ss >= 0 && se >= 0 {
					subject = text[ss:se]
				}
			}
			// Comma-formatted numbers ("9,319") must compare equal to
			// the bare integer (9319) stored in facts.yaml. Strip
			// thousands separators before the facts walk.
			if p.category == "quantitative" {
				subject = strings.ReplaceAll(subject, ",", "")
			}

			claim := Claim{
				Text:      strings.TrimRight(matchText, ".,;!?"),
				Category:  p.category,
				StartByte: start,
				EndByte:   end,
			}

			if p.verdict != VerdictPass {
				claim.Verdict = p.verdict
				if p.verdict == VerdictOpinion {
					claim.Note = "preference / value statement; not verifiable"
				}
			} else {
				if path, val, ok := findInFacts(facts, subject); ok {
					claim.Verdict = VerdictVerified
					claim.EvidencePath = path
					claim.EvidenceValue = val
				} else {
					claim.Verdict = VerdictUnverified
				}
			}
			out = append(out, claim)
		}
	}

	// Sort by source order for stable test output. Forbidden hits
	// were collected before pattern hits so source order has to be
	// re-imposed.
	sortClaimsBySource(out)

	return DetectionResult{
		Claims:  out,
		Summary: summarize(out),
	}
}

type span struct{ start, end int }

func findAllOccurrences(haystack, needle string) []span {
	if needle == "" {
		return nil
	}
	lowerH := strings.ToLower(haystack)
	lowerN := strings.ToLower(needle)
	var out []span
	from := 0
	for {
		i := strings.Index(lowerH[from:], lowerN)
		if i < 0 {
			return out
		}
		start := from + i
		end := start + len(needle)
		// #85: require word-boundary anchoring so a rule needle like
		// "Terraform" doesn't match "Terraforming code" and "production
		// Go" doesn't match "production Golang". Boundary check only
		// fires on edges where the needle itself starts/ends with a
		// word char — quoted-phrase needles that end in punctuation
		// don't need anchoring on that side.
		if !hasWordBoundaries(haystack, start, end, needle) {
			from = start + 1 // advance past this spurious hit
			continue
		}
		out = append(out, span{start: start, end: end})
		from = end
		if from >= len(haystack) {
			return out
		}
	}
}

// hasWordBoundaries reports whether [start, end) inside haystack is
// flanked by word boundaries. A "word boundary" exists when the
// adjacent character is a non-word character (or the string edge)
// AND the corresponding edge of the needle IS a word character.
// Pure punctuation needles get no boundary requirement on their
// punctuation edges, so a rule like "❌ \"foo bar\"" still matches.
func hasWordBoundaries(haystack string, start, end int, needle string) bool {
	if len(needle) == 0 {
		return true
	}
	leftOK := !isWordByte(needle[0]) || start == 0 || !isWordByte(haystack[start-1])
	rightOK := !isWordByte(needle[len(needle)-1]) || end >= len(haystack) || !isWordByte(haystack[end])
	return leftOK && rightOK
}

// isWordByte mirrors regex \w semantics for ASCII. Forbidden-claim
// rules are operator-authored in English; ASCII coverage handles the
// universe of cases that have shown up in dogfood. Non-ASCII letters
// fall through to "not a word char" which is the safer default for
// boundary checks (more boundaries → fewer false matches).
func isWordByte(b byte) bool {
	switch {
	case b >= 'A' && b <= 'Z':
		return true
	case b >= 'a' && b <= 'z':
		return true
	case b >= '0' && b <= '9':
		return true
	case b == '_':
		return true
	}
	return false
}

// temporalPreps are lowercase preposition+space strings that, when
// immediately preceding a bare 4-digit year, indicate temporal context
// ("in 2010", "since 2015") rather than a factual claim.
var temporalPreps = []string{
	"in ", "since ", "from ", "until ", "by ", "before ", "after ", "during ",
}

// isTemporalYearContext reports whether the character immediately before
// position pos in text is part of a temporal preposition phrase. Used by
// Detect to suppress bare-year date claims that are calendar references.
func isTemporalYearContext(text string, pos int) bool {
	if pos == 0 {
		return false
	}
	prefix := strings.ToLower(text[:pos])
	for _, prep := range temporalPreps {
		if strings.HasSuffix(prefix, prep) {
			return true
		}
	}
	return false
}

func spanOverlapsAny(start, end int, claims []Claim) bool {
	for _, c := range claims {
		if start < c.EndByte && end > c.StartByte {
			return true
		}
	}
	return false
}

func sortClaimsBySource(claims []Claim) {
	for i := 1; i < len(claims); i++ {
		for j := i; j > 0 && claims[j].StartByte < claims[j-1].StartByte; j-- {
			claims[j], claims[j-1] = claims[j-1], claims[j]
		}
	}
}

func summarize(claims []Claim) Summary {
	s := Summary{Total: len(claims)}
	for _, c := range claims {
		switch c.Verdict {
		case VerdictVerified:
			s.Verified++
		case VerdictUnverified:
			s.Unverified++
		case VerdictForbidden:
			s.Forbidden++
		case VerdictOpinion:
			s.Opinion++
		case VerdictContradiction:
			s.Contradiction++
		}
	}
	return s
}

// findInFacts walks facts.yaml for any node whose scalar value equals
// needle (case-insensitive for strings, exact for numbers/bools).
// Returns the dotted path, the matched value, and a found flag.
//
// v0.6 logic is intentionally simple: substring lookup is too greedy
// (would match "Go" inside "Goth"), and semantic similarity is
// out of scope. The exact-string-anywhere walk is what the roadmap
// example expects ("I shipped Go in production" → VERIFIED when
// tech_stack.primary_language == "Go").
func findInFacts(facts *Facts, needle string) (string, any, bool) {
	if facts == nil || len(facts.Root) == 0 || needle == "" {
		return "", nil, false
	}
	return walkFacts(facts.Root, "", needle)
}

func walkFacts(node any, path, needle string) (string, any, bool) {
	switch v := node.(type) {
	case map[string]any:
		for k, child := range v {
			childPath := k
			if path != "" {
				childPath = path + "." + k
			}
			if p, val, ok := walkFacts(child, childPath, needle); ok {
				return p, val, ok
			}
		}
	case []any:
		for i, child := range v {
			childPath := fmt.Sprintf("%s[%d]", path, i)
			if p, val, ok := walkFacts(child, childPath, needle); ok {
				return p, val, ok
			}
		}
	case string:
		if strings.EqualFold(v, needle) {
			return path, v, true
		}
	case time.Time:
		// yaml.v3 parses bare YYYY-MM-DD values as time.Time. Match
		// the canonical date form so a YYYY-MM-DD date claim from the
		// detector lines up with a date scalar in facts.yaml.
		if v.Format("2006-01-02") == needle {
			return path, v, true
		}
	case int, int64, float64, bool:
		if fmt.Sprint(v) == needle {
			return path, v, true
		}
	}
	return "", nil, false
}
